---
# tasks file for roles/91de0n.postgrespro_initdb
- block:

  - name: create project locale
    locale_gen: name={{ postgrespro_initdb_locale }} state=present
    register: result

  - name: restart postgres after creating locale
    service: name="postgresql@{{postgrespro_version}}-main" state=restarted
    when: result.changed

  - name: create a user
    postgresql_user:
      name: "{{ postgrespro_initdb_dbuser }}"
      password: "{{ postgrespro_initdb_dbpass }}"
    become_user: postgres

  - name: create the database
    postgresql_db:
      name: "{{ postgrespro_initdb_dbname }}"
      owner: "{{ postgrespro_initdb_dbuser }}"
      encoding: UTF8
      lc_ctype: "{{ postgrespro_initdb_locale }}"
      lc_collate: "{{ postgrespro_initdb_locale }}"
      template: template0
    become_user: postgres

  become: True
