
- name: copy Vagrantfile
  template:
    src: "{{item}}"
    dest: "{{project_deploy_directory}}/Vagrantfile"
  with_first_found:
    - files:
        - "{{vagrant_template_vagrantfile}}"
      skip: true
  notify: "reload and provision vagrant"
  tags: provision
