- name: ensure local project workspace exists
  file:
    path: "{{project_deploy_directory}}"
    state: directory
  tags: provision

- include_tasks: copy_vagrantfile.yml ansible_provision=stubprovision.yml

- name: execute vagrant up against Vagrantfile
  command: "vagrant up"
  args:
    chdir: "{{project_deploy_directory}}"
  tags: provision

- name: execute vagrant provision to ensure inventory is refreshed
  command: "vagrant provision"
  args:
    chdir: "{{project_deploy_directory}}"
  tags: provision

- name: ensure local inventory link does not exists
  file:
    path: "{{project_ansible_directory}}/inventory/{{ pipeline }}"
    state: absent
  tags: provision

- name: link local inventory into deploy directory
  file:
    src: "{{project_deploy_directory}}/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"
    dest: "{{project_ansible_directory}}/inventory/{{ pipeline }}"
    state: link
  tags: provision

- include_tasks: copy_vagrantfile.yml ansible_provision=site.yml
