---
# tasks file for roles/91de0n.postgrespro
- block:

  - name: add postgrespro repo key
    apt_key:
      url: "http://repo.postgrespro.ru/pgpro-{{postgrespro_version}}/keys/GPG-KEY-POSTGRESPRO"
      state: present

  - name: add postgrespro repo
    apt_repository:
      repo: "deb http://repo.postgrespro.ru/pgpro-{{postgrespro_version}}/ubuntu {{ansible_distribution_release}} main"
      filename: postgrespro
      state: present
      update_cache: yes

  - name: install apt packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - libpq-dev
      - postgrespro
      - python-psycopg2

  - name: copy available configs
    template: >
      src="{{item.path}}" dest="/etc/postgresql/{{postgrespro_version}}/main/{{item.file}}"
      owner=postgres group=postgres mode=0640
    with_items:
      - "{{postgrespro_configs}}"
    when: postgrespro_configs is defined
    register: result

  - name: restart postgres after changes in configs
    service: name="postgresql@{{postgrespro_version}}-main" state=restarted
    when: result.changed

  - name: enable postgres at boot
    service: name="postgresql@{{postgrespro_version}}-main" state=started enabled=yes

  become: True
