---
# tasks file for roles/91de0n.postgrespro
- block:

  - name: add postgrespro repo key
    apt_key:
      url: "http://repo.postgrespro.ru/pgpro-{{project_postgres_version}}/keys/GPG-KEY-POSTGRESPRO"
      state: present

  - name: add postgrespro repo
    apt_repository:
      repo: "deb http://repo.postgrespro.ru/pgpro-{{project_postgres_version}}/ubuntu {{ansible_distribution_release}} main"
      filename: postgrespro
      state: present
      update_cache: yes

  - name: install apt packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - libpq-dev
      - postgrespro
      - python-psycopg2

  - name: copy pg_hba.conf if template exists
    template: >
      src="{{item}}" dest="/etc/postgresql/{{project_postgres_version}}/main/pg_hba.conf"
      owner=postgres group=postgres mode=0640
    with_first_found:
      - files:
          - "{{postgrespro_template_pghbaconf}}"
        skip: true
    notify: restart postgres

  - name: copy postgresql.conf if template exists
    template: >
      src="{{item}}" dest="/etc/postgresql/{{project_postgres_version}}/main/postgresql.conf"
      owner=postgres group=postgres mode=0640
    with_first_found:
      - files:
          - "{{postgrespro_template_postgresqlconf}}"
        skip: true
    notify: restart postgres

  - name: enable postgres at boot
    service: name="postgresql" state=started enabled=yes
    # service: name="postgresql@{{project_postgres_version}}-main" state=started enabled=yes

  become: True
