---
# tasks file for roles/postgres_pro_install
- block:

  - name: Add postgrespro repo key
    apt_key:
      url: "http://repo.postgrespro.ru/pgpro-{{postgrespro_version}}/keys/GPG-KEY-POSTGRESPRO"
      state: present

  - name: Add postgrespro repo
    apt_repository:
      repo: "deb http://repo.postgrespro.ru/pgpro-{{postgrespro_version}}/ubuntu {{ansible_distribution_release}} main"
      filename: postgrespro
      state: present
      update_cache: yes

  - name: install apt packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - libpq-dev
      - postgrespro
      - python-psycopg2

  - name: copy pg_hba.conf
    template: >
      src={{postgrespro_pghba}} dest="/etc/postgresql/{{postgrespro_version}}/main/pg_hba.conf"
      owner=postgres group=postgres mode=0640
    when: postgrespro_pghba is defined

  - name: copy postgresql.conf
    template: >
      src={{postgrespro_postgresql}} dest="/etc/postgresql/{{postgrespro_version}}/main/postgresql.conf"
      owner=postgres group=postgres mode=0640
    when: postgrespro_postgresql is defined

  - name: enable postgres at boot, restart it
    service: name="postgresql@{{postgrespro_version}}-main" state=restarted enabled=yes

  become: True
