---
djangopg_template_localsettingspy: local_settings.py.j2
project_settings_path: "{{ project_path }}/{{ project_name }}"
project_python: "{{ project_venv_path }}/bin/python"
project_manage: "{{ project_python }} {{ project_path }}/manage.py"
