---
# tasks file for roles/postgres_pro_createdb
- block:
  
  - name: create project locale
    locale_gen: name={{ locale }} state=present
    register: result

  - name: restart postgres after creating locale
    service: name="postgresql@{{postgrespro_version}}-main" state=restarted
    when: result.changed

  - name: create a user
    postgresql_user:
      name: "{{ database_user }}"
      password: "{{ db_pass }}"
    become_user: postgres

  - name: create the database
    postgresql_db:
      name: "{{ database_name }}"
      owner: "{{ database_user }}"
      encoding: UTF8
      lc_ctype: "{{ locale }}"
      lc_collate: "{{ locale }}"
      template: template0
    become_user: postgres

  become: True
