---

- name: install packages needed for deployment
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - git
    - python3-pip

- name: check out git repository of project, clone if needed
  git: repo={{ djangopg_repo_url }} dest={{ djangopg_repo_path }} accept_hostkey=yes force=yes

- name: install python3 virtualenvs
  pip: name={{ item }} state=latest executable="pip3"
  with_items:
    - virtualenv
    - virtualenvwrapper
  become: True

- name: install required python3 packages into project virtualenv
  pip: name={{ item }} virtualenv={{ djangopg_venv_path }}   virtualenv_python=python3
  with_items:
    - psycopg2
    - django

- name: generate the settings file
  template: src=local_settings.py.j2 dest={{ djangopg_settings_path }}/local_settings.py

- name: apply migrations to create the database, collect static content
  django_manage:
    command: "{{ item }}"
    app_path: "{{ djangopg_proj_path }}"
    virtualenv: "{{ djangopg_venv_path }}"
  with_items:
    - makemigrations
    - migrate
    - collectstatic
