---

- name: install packages needed for deployment
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - git

- stat: path="{{project_path}}/.git"
  register: p

- name: check out git repository of project, clone if needed
  git: repo="{{ project_repo_url }}" dest="{{ project_repo_path }}" accept_hostkey=yes force=yes version=develop
  when: p.stat.exists == false

- name: install required python3 packages into project virtualenv
  pip: name={{ item }} virtualenv={{ project_venv_path }}   virtualenv_python="python{{project_python_version}}"
  with_items:
    - psycopg2
    - django

- stat: path="{{ project_settings_path }}/local_settings.py"
  register: p

- name: generate the settings file
  template: src={{item}} dest={{ project_settings_path }}/local_settings.py
  with_first_found:
    - files:
        - "{{djangopg_template_localsettingspy}}"
      skip: True
  when: p.stat.exists == false

- name: apply migrations to create the database, collect static content
  django_manage:
    command: "{{ item }}"
    app_path: "{{ project_path }}"
    virtualenv: "{{ project_venv_path }}"
  with_items:
    - makemigrations
    - migrate
    - collectstatic
