---

- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - git
    - memcached
    - supervisor


- name: check out the repository on the host
  git: repo={{ mezzanine_repo_url }} dest={{ mezzanine_repo_path }} accept_hostkey=yes
